import PDFDocument from 'pdfkit';

let browserInstance = null;

async function getBrowser() {
  if (!browserInstance || !browserInstance.isConnected()) {
    const { chromium } = await import('playwright');
    browserInstance = await chromium.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-gpu'
      ]
    });
    browserInstance.on('disconnected', () => {
      browserInstance = null;
    });
  }
  return browserInstance;
}

/**
 * Structured PDFKit fallback generator.
 * Produces a styled vector document with borders, headers, and tables
 * if the Chromium browser engine is unavailable.
 */
function generatePdfKitFallback(htmlContent) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margin: 30
      });

      const chunks = [];
      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Clean HTML tags and decode common entities
      const cleanText = htmlContent
        .replace(/<style[\s\S]*?<\/style>/gi, '')
        .replace(/<script[\s\S]*?<\/script>/gi, '')
        .replace(/<br\s*[\/]?>/gi, '\n')
        .replace(/<\/p>/gi, '\n')
        .replace(/<\/div>/gi, '\n')
        .replace(/<\/tr>/gi, '\n')
        .replace(/<\/h[1-6]>/gi, '\n')
        .replace(/<[^>]+>/g, ' ')
        .replace(/&#8377;/g, 'Rs. ')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .replace(/[ \t]+/g, ' ')
        .replace(/\n\s+/g, '\n')
        .replace(/\n{2,}/g, '\n')
        .trim();

      // Top bar
      doc.rect(30, 30, 535, 4).fill('#2563EB');

      // Title
      doc.fillColor('#0F172A').fontSize(16).font('Helvetica-Bold').text('INVOICE / BILL', 30, 45);
      doc.fontSize(8).font('Helvetica').fillColor('#64748B').text('MEMOTRIX ENTERPRISE BILLING', 30, 65);

      doc.moveTo(30, 80).lineTo(565, 80).strokeColor('#E2E8F0').stroke();

      const lines = cleanText.split('\n').filter(l => l.trim().length > 0);
      let y = 95;

      doc.fillColor('#1E293B').fontSize(9).font('Helvetica');
      for (const line of lines) {
        if (y > 770) break; // Keep strictly within 1 page

        const isHeaderLine = line.match(/(TAX INVOICE|BILL TO|INVOICE DETAILS|TOTAL|TERMS|ACKNOWLEDGMENT)/i);
        if (isHeaderLine) {
          y += 4;
          doc.font('Helvetica-Bold').fillColor('#2563EB').text(line.trim(), 30, y);
          doc.font('Helvetica').fillColor('#1E293B');
          y += 14;
        } else {
          doc.text(line.trim(), 30, y, { width: 535 });
          y += 12;
        }
      }

      // Footer
      doc.fontSize(8).fillColor('#94A3B8').text('Generated by Memotrix Billing System', 30, 790, {
        align: 'center',
        width: 535
      });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

/**
 * Generate a pixel-perfect, single-page A4 PDF using Playwright Chromium.
 * Falls back safely to PDFKit if browser launch encounters errors.
 */
export async function generateInvoicePdf(htmlContent) {
  try {
    const browser = await getBrowser();
    const page = await browser.newPage();

    // Set viewport to standard A4 proportions (approx 794x1123 at 96 DPI)
    await page.setViewportSize({ width: 794, height: 1123 });
    await page.setContent(htmlContent, { waitUntil: 'networkidle' });

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      preferCSSPageSize: true
    });

    await page.close();
    return pdfBuffer;
  } catch (err) {
    console.warn('[PDF SERVICE] Playwright Chromium error. Utilizing structured PDFKit fallback generator:', err.message);
    return generatePdfKitFallback(htmlContent);
  }
}

export default {
  generateInvoicePdf
};
